### ISSUE TITLE
Incorrect test assertion for Chapter4, Task 8 

### ISSUE THREAD

**Issue by CharlesSchimmel** [kowainik/learn4haskell#236]
The following assertion in Chapter 4, Task 8 is incorrect, it should be `Nothing` as well

https://github.com/kowainik/learn4haskell/blob/0bdad6f127ab5d7eb357a9ca3fcca2f1dd45caf8/test/Test/Chapter4.hs#L59

**Comment by vrom911** [comment]
This is a correct assertion and we expect the solution to respect this test case.

**Comment by CharlesSchimmel** [comment]
Oh no how embarrassing for me lol. If that's the case, I don't think the prompt for the task makes that clear. The prompt doesn't indicate to return `m False` if the first term is `False` instead of lifting the whole function into `m`, which would differ it from something from `liftM2 (&&)`

**Comment by vrom911** [comment]
This is the lifted version of `&&` which is also lazy, so no surprises in how it works. You don't expect `False && undefined` fail, you expect it to return `False`, so this is a sane assumption. We already specified the constraint of `Monad` in the function as well, which is also a hint. We don't want to provide problem solutions in the task description. We can always explain everything in the review if people would have questions about the task.

**Comment by CharlesSchimmel** [comment]
I'm worried that this is confusing as it differs from something like `(&&) <$> (Just False) <*> Nothing` as well, and communicates the idea that all lifted lazy functions will act that way. I don't know enough to articulate it, but it seems that even though `(&&)` is lazy on its own, lifted versions still evaluate the context of the second term. Anyway I won't belabor this more, thanks for taking the time to explain, and these exercises were great.

**Comment by vrom911** [comment]
I am not sure what you are trying to prove in here, but your solution `(&&) <$> (Just False) <*> Nothing` doesn't even use `Monad`. That means that it just could not be lazy, as laziness is only achievable in here due to `Monad`. `Applicative` apriori won't give you that.
Moreover, this is only an exercise. It is not the library that you have to use. If you think that all people are doing a poor job implementing this function not your way, try to open this issue in all the libraries that provide such a function: [`directory`](https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory-Internal.html#v:andM), [`extra`](https://hackage.haskell.org/package/extra-1.7.8/docs/Control-Monad-Extra.html#v:-38--38--94-), [`protolude`](https://hackage.haskell.org/package/protolude-0.3.0/docs/Protolude.html#v:-38--38--94-) and many many more!

Here is not the place to push your visions on laziness and strictness as this is the learning material on Monads that we provide.

**Comment by CharlesSchimmel** [comment]
I'm sorry if I came off as adversarial, I am just trying to reconcile what I thought I understood with the explanation you gave. I'm am 
barely past total beginner and thought I found something that was overlooked, and trying to help and learn more.
