### ISSUE TITLE
Odd test output results

### ISSUE THREAD

**Issue by bitwombat** [kowainik/learn4haskell#498]
Hi, first thanks for making this kowainik!

I'm getting some weird output from the tests:

```
src/Chapter1.hs:221: failure in expression `:t (&&)'
expected: (&&) :: Bool -> Boolean -> Bool
but got: (&&) :: Bool -> Bool -> Bool
```

Looks to me like the "expected" (which is my incorrect answer) is switched with "but got".

Also, the output seems to jump around, going from complaining about line 221 to line 305, even though there are many tests between there:

```
Test suite doctest-chapter1: RUNNING...
src/Chapter1.hs:221: failure in expression `:t (&&)'
expected: (&&) :: Bool -> Boolean -> Bool
 but got: (&&) :: Bool -> Bool -> Bool
                              ^
src/Chapter1.hs:305: failure in expression `(3 + 5) < 10'
expected: <INSERT THE RESULT INSTEAD OF THE TEXT>
 but got: True
          ^
```
***Now, this could be my fault***, because I needed to bump up base to 4.15, and doctest to 0.18 in order to get the `cabal build` to run in docker/haskell.

**Comment by chshersh** [comment]
Hi @bitwombat 👋🏻 

As you can see, the "expected" output "Bool -> Boolean -> Bool" is incorrect because Haskell doesn't have standard type `Boolean` and it should be `Bool`. In this context, "expected" is your code because this is "what you **expect** from the test" and "but got" is what GHC actually gives you.

The doctest output can be confusing but I hope my comment helps you a bit 🙂

**Comment by bitwombat** [comment]
Yes, an intentional injected error to show the problem.
That's backwards what all other testing frameworks use for 'expected' and 'actual' but I can calibrate myself.

**Comment by bitwombat** [comment]
Actually, shouldn't have closed it - the seemingly random order it's testing in (described in the original text) is also confusing for a newbie...

**Comment by chshersh** [comment]
@bitwombat I believe, this is happening because [doctest](https://github.com/sol/doctest) runs tests in a non-deterministic order. Probably for performance reasons. Unfortunately, nothing we can do here. I can recommend opening an issue in `doctest` if you want to discuss the possibility of having an option for running tests in a sequence.
