### ISSUE TITLE
are my solutions be mentored ? 

### ISSUE THREAD

**Issue by RoelofWobben** [kowainik/learn4haskell#507]
Hello, 

I solved  chapter1 2 days ago and wonder if my solutions be mentored 

Chapter1 : https://github.com/kowainik/learn4haskell/pull/502
Chapter2 : https://github.com/kowainik/learn4haskell/pull/503

**Comment by chshersh** [comment]
@RoelofWobben We offer this course for free and we review solutions for free in our free time. So we can mentor only when we have the capacity to do so. Moreover, it's been only 2 days since you opened PRs with your solutions, and, honestly, it's pretty demanding to ask people to spend their free time to review your solutions that urgently. Such an attitude doesn't increase the motivation to continue working on this course.

If you want to check our solutions to all the tasks and compare your solutions with the existing ones, you can check other branches in this repository:

* https://github.com/kowainik/learn4haskell/branches
