### ISSUE TITLE
[error] Function Definition in GHCi on Linux 5.8

### ISSUE THREAD

**Issue by nasirhm** [kowainik/learn4haskell#59]
Hey Awesome people, First of all thank you very much for the amazing idea of learning Haskell in 4 PRs with Hacktoberfest (I 
absolutely love the Idea :heart: )

I'm trying to define a function in Glassgow Haskell Compiler's REPL by executing the following line : 

```
prelude> roundSubtract :: Double -> Int -> Int
```

and It results in the following error: 

```
<interactive>:3:1: error:
    • No instance for (Show (Double -> Int -> Int))
        arising from a use of ‘print’
        (maybe you haven't applied a function to enough arguments?)
    • In a stmt of an interactive GHCi command: print it
```

On the tutorial, In `Chapter1.hs`, on line 358, It asks to do it.

CC: @chshersh @vrom911

**Comment by chshersh** [comment]
Hi @nasirhm! When the section describes top-level function definitions and type-signatures, it talks about writing them inside a file, not inside REPL. GHCi can parse only one line at a time by default. But a function definition requires two lines: a type signature and a function body. That's why creating new functions in GHCi is awkward, and the course assumes that you will implement new functions inside a module, and then load the module in GHCi.

If you start fresh GHCi, and try to insert this string, you will get the following error:

```haskell
Prelude> roundSubtract :: Double -> Int -> Int

<interactive>:8:1: error:
    Variable not in scope: roundSubtract :: Double -> Int -> Int
```

What you probably did, is that you've copied the implementation of `roundSubtract` without the type, GHCi inferred its type and recognized as valid, and now you're trying to show a value `roundSubtract` which is a function, but Haskell can't display functions in runtime.

Let me know if clarifies some things, or whether you need more help :slightly_smiling_face:

**Comment by vasylzhmurko** [comment]
Hello guys, maybe its possible to write function definition with ";" inline. 
Example: myFunction :: String -> String; myFunction string = "Hello " ++ string

**Comment by chshersh** [comment]
@vasylzhmurko Yes, you can write a function type signature and its implementation in a single line by separating type signature and body with a semicolon `;`. Exactly as @vasylzhmurko wrote, this is valid Haskell syntax inside GHCi.

You can also use special GHCi commands `:{` and `:}` to start and end multiline blocks, we mention them in Chapter Three.

Defining functions in one-line in GHCi sometimes useful, but it's not how you usually write them in the module. Also, once you start having more complex bodies (guards, nested if-then-else expressions, etc.), writing everything in a single line becomes very awkward.

I'm closing this issue, as the question seems to be answered :slightly_smiling_face: Let us know if you have other questions!

**Comment by nasirhm** [comment]
> GHCi can parse only one line at a time by default.

Nice catch, Will keep it in mind for the next examples :+1: 

Thank You for answering and information @vasylzhmurko and @chshersh :)
